name: bandit

on:
  push:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: install utils
        run: |
          sudo apt-get update
          sudo apt-get install moreutils -y
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install bandit
        run: pip install bandit
      - name: Checkout
        uses: actions/checkout@v3
      - name: run bandit
        run: |
          bandit django_dynamic_shields -r -o ./bandit.txt -f txt
      - name: Archive bandit log
        if: always()
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: bandit-report
          path: ./bandit.txt
