name: pyt

on:
  push:

jobs:
  pyt:
    runs-on: ubuntu-latest
    steps:
      - name: install utils
        run: |
          sudo apt-get update
          sudo apt-get install moreutils -y
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install python-taint
        run: pip install python-taint
      - name: Checkout
        uses: actions/checkout@v3
      - name: run pyt
        run: |
          pyt -a D -o pyt.txt ./
      - name: Archive pyt log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pyt-report
          path: ./pyt.txt
